# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "407e9cdba221bb187c67447be9f200ba"
name = "MobileX App Builder"
handle = "mobilex-app-builder"
application_url = "https://browsing-identification-organizational-marijuana.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_draft_orders,write_draft_orders,read_orders,write_orders,read_customers,write_customers,read_themes,write_themes"

[auth]
redirect_urls = ["https://browsing-identification-organizational-marijuana.trycloudflare.com/auth/callback", "https://browsing-identification-organizational-marijuana.trycloudflare.com/auth/shopify/callback", "https://browsing-identification-organizational-marijuana.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
